- hosts: wxnacytest
  remote_user: root
  tasks:
  - name: Get path
    shell: |
        pwd
    register: result
  - name: Get debug info
    debug: var=result.stdout verbosity=0


# debug 指定输出 result.stdout
# 输出结果 https://s1.ax1x.com/2020/06/03/td3UxI.png
